// <auto-generated>
// Generated by Bishop.Life.SchemaCodegen from Bishop.Life.Core/Schema (card #1077).
// Edits to this file are overwritten on the next build — change the C# records
// under life/src/Bishop.Life.Core/Schema/ and rebuild Bishop.Life.App instead.
// </auto-generated>

export type Horizon =
  | "today"
  | "thisWeek"
  | "thisMonth"
  | "someday";

export interface Area {
  id: string;
  name: string;
  color: string;
  goals: Goal[];
}

export interface BareEnvelope {
  type: string;
}

export interface Goal {
  id: string;
  name: string;
  horizon?: string | null;
  actions: LifeAction[];
}

export interface InboxItem {
  id: string;
  text: string;
  capturedAt: string;
}

export interface LifeAction {
  id: string;
  title: string;
  starred: boolean;
  done: boolean;
  horizon: Horizon;
  createdAt: string;
  completedAt?: string | null;
}

export interface LifePlan {
  schema: string;
  meta: Meta;
  areas: Area[];
  inbox: InboxItem[];
  standups: Standup[];
}

export interface Meta {
  createdAt: string;
  lastStandupAt?: string | null;
}

export interface MutateRequestEnvelope {
  type: string;
  plan: LifePlan;
}

export interface PlanStateEnvelope {
  status: string;
  filePath: string;
  plan?: LifePlan | null;
  standupInFlight: boolean;
  addInFlight: boolean;
  error?: string | null;
}

export interface SpeakEnvelope {
  type: string;
  pcmBase64?: string | null;
  pcmSampleRateHz: number;
  durationMs: number;
}

export interface Standup {
  id: string;
  at: string;
  reflection: string;
  focusToday: string[];
}

export interface StandupEndEnvelope {
  type: string;
}

export interface SystemNoteEnvelope {
  type: string;
  text: string;
}

export interface TerminalInputRequestEnvelope {
  type: string;
  data: string;
  submit: boolean;
}

export interface TerminalResizeRequestEnvelope {
  type: string;
  cols: number;
  rows: number;
}

export interface TranscriptEventEnvelope {
  type: string;
  kind: string;
  text: string;
}
