using System.Text;
using Bishop.Core;
using Bishop.Data;
using Microsoft.EntityFrameworkCore;

namespace Bishop.App.Terminal;

public sealed class WorkspaceContextSeeder : IWorkspaceContextSeeder
{
    internal const string BishopContextFileName = "BISHOP_CONTEXT.md";
    internal const string ContextFileName = "CONTEXT.md";
    internal const string PointerLine = "> See [BISHOP_CONTEXT.md](./BISHOP_CONTEXT.md) — Bishop CLI reference and live workspace state for LLM agents.";
    internal const string PointerMarker = "BISHOP_CONTEXT.md";

    private readonly BishopDbContext _db;

    public WorkspaceContextSeeder(BishopDbContext db) => _db = db;

    public async Task SeedAsync(string workspacePath, CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(workspacePath) || !Directory.Exists(workspacePath))
            return;

        var fullPath = Path.GetFullPath(workspacePath);
        var workspace = await ResolveWorkspaceAsync(fullPath, cancellationToken);
        if (workspace is null) return;

        var bishopFile = Path.Combine(fullPath, BishopContextFileName);
        File.WriteAllText(bishopFile, BuildBishopContext(workspace));

        var contextFile = Path.Combine(fullPath, ContextFileName);
        var existing = File.Exists(contextFile) ? File.ReadAllText(contextFile) : null;
        var merged = EnsureContextMd(existing, workspace);
        if (!string.Equals(existing, merged, StringComparison.Ordinal))
            File.WriteAllText(contextFile, merged);
    }

    private async Task<Workspace?> ResolveWorkspaceAsync(string fullPath, CancellationToken cancellationToken)
    {
        var workspaces = await _db.Workspaces
            .AsNoTracking()
            .Include(w => w.Lanes.OrderBy(l => l.Position))
            .Include(w => w.Tags.OrderBy(t => t.Name))
            .ToListAsync(cancellationToken);

        return workspaces.FirstOrDefault(w =>
            string.Equals(Path.GetFullPath(w.Path), fullPath, StringComparison.OrdinalIgnoreCase));
    }

    internal static string BuildBishopContext(Workspace workspace)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# BISHOP_CONTEXT — {workspace.Name}");
        sb.AppendLine();
        sb.AppendLine("> Auto-generated by Bishop on every workspace launch. Do not edit by hand —");
        sb.AppendLine("> changes will be overwritten. Update the workspace itself (via the app or CLI)");
        sb.AppendLine("> and relaunch to refresh.");
        sb.AppendLine();
        sb.AppendLine("This file describes the current Bishop workspace so an LLM agent working in");
        sb.AppendLine("this directory has everything it needs to interact with the board correctly.");
        sb.AppendLine();

        sb.AppendLine("## This workspace");
        sb.AppendLine();
        sb.AppendLine($"- **Name:** {workspace.Name}");
        sb.AppendLine($"- **Path:** `{workspace.Path}`");
        if (!string.IsNullOrWhiteSpace(workspace.GitHubRepo))
            sb.AppendLine($"- **GitHub:** `{workspace.GitHubRepo}`");
        sb.AppendLine();

        sb.AppendLine("### Lanes");
        sb.AppendLine();
        if (workspace.Lanes.Count == 0)
        {
            sb.AppendLine("_No lanes yet._");
        }
        else
        {
            var i = 1;
            foreach (var lane in workspace.Lanes.OrderBy(l => l.Position))
            {
                var suffix = lane.IsSystem ? " _(system)_" : "";
                sb.AppendLine($"{i}. {lane.Name}{suffix}");
                i++;
            }
        }
        sb.AppendLine();

        sb.AppendLine("### Tags");
        sb.AppendLine();
        if (workspace.Tags.Count == 0)
        {
            sb.AppendLine("_No tags yet._");
        }
        else
        {
            foreach (var tag in workspace.Tags.OrderBy(t => t.Name, StringComparer.OrdinalIgnoreCase))
                sb.AppendLine($"- `{tag.Name}`");
        }
        sb.AppendLine();

        sb.AppendLine("## Card model");
        sb.AppendLine();
        sb.AppendLine("Bishop tracks work as **cards** inside **lanes** on a per-workspace kanban board.");
        sb.AppendLine("Cards are addressed by their workspace-scoped Number, written as `#N` (e.g. `#42`).");
        sb.AppendLine("Card identifiers also accept the first 8 hex characters of the card's GUID.");
        sb.AppendLine("Tags are workspace-scoped and attach to cards via the `CardTag` join.");
        sb.AppendLine();

        sb.AppendLine("### Card body convention");
        sb.AppendLine();
        sb.AppendLine("Bodies use a structured, single-line-per-paragraph format. Paragraphs are");
        sb.AppendLine("separated by blank lines (or literal `\\n` when passing via the CLI):");
        sb.AppendLine();
        sb.AppendLine("```");
        sb.AppendLine("<what changes, 1 sentence>.");
        sb.AppendLine("Decided: <choice> over <alternative> because <reason>.");
        sb.AppendLine("Acceptance: <criteria>.");
        sb.AppendLine("```");
        sb.AppendLine();
        sb.AppendLine("Omit the `Decided:` clause when no real tradeoff was discussed.");
        sb.AppendLine();

        sb.AppendLine("## CLI quick reference");
        sb.AppendLine();
        sb.AppendLine("All commands accept `-w <workspace>` to target a specific workspace; without it");
        sb.AppendLine("they resolve from the current working directory.");
        sb.AppendLine();

        sb.AppendLine("### Workspace");
        sb.AppendLine();
        sb.AppendLine("- `bishop workspace list [--json]`");
        sb.AppendLine("- `bishop workspace current [--json]` — resolves the workspace from cwd by ancestor match");
        sb.AppendLine("- `bishop workspace init [--path <dir>] [--name <name>]` — register a directory; idempotent");
        sb.AppendLine("- `bishop workspace set-github <owner/repo>` — link the workspace to a GitHub repo");
        sb.AppendLine();

        sb.AppendLine("### Card");
        sb.AppendLine();
        sb.AppendLine("- `bishop card list [--json]`");
        sb.AppendLine("- `bishop card view <id> [--json]`");
        sb.AppendLine("- `bishop card add --lane <name> --title <text> [--description <text> | --description-file <path>] [--tag <name>...]`");
        sb.AppendLine("- `bishop card move <id> --to-lane <name> --to-position <int>`");
        sb.AppendLine("- `bishop card edit <id> [--title <t>] [--description <d> | --description-file <path>] [--tag <name>...] [--clear-tags]`");
        sb.AppendLine("- `bishop card claim [--lane <name>] [--json]` — pop the top card of a lane into \"Doing\"");
        sb.AppendLine("- `bishop card push <id>` — create a GitHub issue for the card");
        sb.AppendLine("- `bishop card close <id>` / `bishop card reopen <id>`");
        sb.AppendLine();

        sb.AppendLine("### Lane");
        sb.AppendLine();
        sb.AppendLine("- `bishop lane list`");
        sb.AppendLine("- `bishop lane add` / `bishop lane rename` / `bishop lane move`");
        sb.AppendLine();

        sb.AppendLine("### Tag");
        sb.AppendLine();
        sb.AppendLine("- `bishop tag list`");
        sb.AppendLine("- `bishop tag add [--colour <hex>]`");
        sb.AppendLine();

        sb.AppendLine("Prefer `--json` output for any command an agent will parse. Pipe multi-line");
        sb.AppendLine("descriptions via `--description-file -` (stdin) to avoid quote escaping.");

        return sb.ToString();
    }

    internal static string EnsureContextMd(string? existing, Workspace workspace)
    {
        if (existing is null)
            return BuildContextMdStub(workspace);

        if (existing.Contains(PointerMarker, StringComparison.Ordinal))
            return existing;

        var newline = existing.Contains("\r\n", StringComparison.Ordinal) ? "\r\n" : "\n";
        var lines = existing.Split('\n').ToList();
        var h1Index = -1;
        for (var i = 0; i < lines.Count; i++)
        {
            var trimmed = lines[i].TrimEnd('\r');
            if (trimmed.StartsWith("# ", StringComparison.Ordinal))
            {
                h1Index = i;
                break;
            }
        }

        var pointerBlock = new[] { "", PointerLine, "" };
        if (h1Index >= 0)
        {
            lines.InsertRange(h1Index + 1, pointerBlock);
        }
        else
        {
            lines.InsertRange(0, new[] { PointerLine, "" });
        }

        return string.Join(newline, lines.Select(l => l.TrimEnd('\r')));
    }

    private static string BuildContextMdStub(Workspace workspace)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# {workspace.Name}");
        sb.AppendLine();
        sb.AppendLine(PointerLine);
        sb.AppendLine();
        sb.AppendLine("<!-- Add a description of this workspace here: what it is, who uses it, and");
        sb.AppendLine("     the conventions a contributor (human or LLM) needs to know. -->");
        return sb.ToString();
    }
}
