using System.Reflection;
using System.Text;
using Bishop.Core;
using Bishop.Data;
using Microsoft.EntityFrameworkCore;

namespace Bishop.App.Terminal;

public sealed class WorkspaceContextSeeder : IWorkspaceContextSeeder
{
    internal const string BishopContextFileName = "BISHOP_CONTEXT.md";
    internal const string ContextFileName = "CONTEXT.md";
    internal const string PointerLine = "> See [BISHOP_CONTEXT.md](./BISHOP_CONTEXT.md) — Bishop CLI reference and live workspace state for LLM agents.";
    internal const string PointerMarker = "BISHOP_CONTEXT.md";

    private readonly BishopDbContext _db;

    public WorkspaceContextSeeder(BishopDbContext db) => _db = db;

    public async Task SeedAsync(string workspacePath, CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(workspacePath) || !Directory.Exists(workspacePath))
            return;

        var fullPath = Path.GetFullPath(workspacePath);
        var workspace = await ResolveWorkspaceAsync(fullPath, cancellationToken);
        if (workspace is null) return;

        var bishopFile = Path.Combine(fullPath, BishopContextFileName);
        File.WriteAllText(bishopFile, BuildBishopContext(workspace));

        var contextFile = Path.Combine(fullPath, ContextFileName);
        var existing = File.Exists(contextFile) ? File.ReadAllText(contextFile) : null;
        var merged = EnsureContextMd(existing, workspace);
        if (!string.Equals(existing, merged, StringComparison.Ordinal))
            File.WriteAllText(contextFile, merged);
    }

    private async Task<Workspace?> ResolveWorkspaceAsync(string fullPath, CancellationToken cancellationToken)
    {
        var workspaces = await _db.Workspaces
            .AsNoTracking()
            .Include(w => w.Lanes.OrderBy(l => l.Position))
            .Include(w => w.Tags.OrderBy(t => t.Name))
            .ToListAsync(cancellationToken);

        return workspaces.FirstOrDefault(w =>
            string.Equals(Path.GetFullPath(w.Path), fullPath, StringComparison.OrdinalIgnoreCase));
    }

    internal static string BuildBishopContext(Workspace workspace)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# BISHOP_CONTEXT — {workspace.Name}");
        sb.AppendLine();
        sb.AppendLine("> Auto-generated by Bishop on every workspace launch. Do not edit by hand —");
        sb.AppendLine("> changes will be overwritten. Update the workspace itself (via the app or CLI)");
        sb.AppendLine("> and relaunch to refresh.");
        sb.AppendLine();
        sb.AppendLine("This file describes the current Bishop workspace so an LLM agent working in");
        sb.AppendLine("this directory has everything it needs to interact with the board correctly.");
        sb.AppendLine();

        sb.AppendLine("## This workspace");
        sb.AppendLine();
        sb.AppendLine($"- **Name:** {workspace.Name}");
        sb.AppendLine($"- **Path:** `{workspace.Path}`");
        if (!string.IsNullOrWhiteSpace(workspace.GitHubRepo))
            sb.AppendLine($"- **GitHub:** `{workspace.GitHubRepo}`");
        sb.AppendLine();

        sb.AppendLine("### Lanes");
        sb.AppendLine();
        if (workspace.Lanes.Count == 0)
        {
            sb.AppendLine("_No lanes yet._");
        }
        else
        {
            var i = 1;
            foreach (var lane in workspace.Lanes.OrderBy(l => l.Position))
            {
                var suffix = lane.IsSystem ? " _(system)_" : "";
                sb.AppendLine($"{i}. {lane.Name}{suffix}");
                i++;
            }
        }
        sb.AppendLine();

        sb.AppendLine("### Tags");
        sb.AppendLine();
        if (workspace.Tags.Count == 0)
        {
            sb.AppendLine("_No tags yet._");
        }
        else
        {
            foreach (var tag in workspace.Tags.OrderBy(t => t.Name, StringComparer.OrdinalIgnoreCase))
                sb.AppendLine($"- `{tag.Name}`");
        }
        sb.AppendLine();

        sb.Append(LoadStaticBody());

        return sb.ToString();
    }

    internal static string LoadStaticBody()
    {
        var assembly = typeof(WorkspaceContextSeeder).Assembly;
        using var stream = assembly.GetManifestResourceStream(
            "Bishop.App.Terminal.BishopContext.static.md")!;
        using var reader = new StreamReader(stream);
        var raw = reader.ReadToEnd();
        return raw.Replace("\r\n", "\n").Replace("\n", Environment.NewLine);
    }

    internal static string EnsureContextMd(string? existing, Workspace workspace)
    {
        if (existing is null)
            return BuildContextMdStub(workspace);

        if (existing.Contains(PointerMarker, StringComparison.Ordinal))
            return existing;

        var newline = existing.Contains("\r\n", StringComparison.Ordinal) ? "\r\n" : "\n";
        var lines = existing.Split('\n').ToList();
        var h1Index = -1;
        for (var i = 0; i < lines.Count; i++)
        {
            var trimmed = lines[i].TrimEnd('\r');
            if (trimmed.StartsWith("# ", StringComparison.Ordinal))
            {
                h1Index = i;
                break;
            }
        }

        var pointerBlock = new[] { "", PointerLine, "" };
        if (h1Index >= 0)
        {
            lines.InsertRange(h1Index + 1, pointerBlock);
        }
        else
        {
            lines.InsertRange(0, new[] { PointerLine, "" });
        }

        return string.Join(newline, lines.Select(l => l.TrimEnd('\r')));
    }

    private static string BuildContextMdStub(Workspace workspace)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# {workspace.Name}");
        sb.AppendLine();
        sb.AppendLine(PointerLine);
        sb.AppendLine();
        sb.AppendLine("<!-- Add a description of this workspace here: what it is, who uses it, and");
        sb.AppendLine("     the conventions a contributor (human or LLM) needs to know. -->");
        return sb.ToString();
    }
}
