using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Bishop.Life.SchemaCodegen;

/// <summary>
/// Roslyn-syntax-only emitter: parses C# source text and produces a single
/// TypeScript declaration string. Syntax-only (no semantic model) keeps the
/// codegen tool's build dependencies and runtime self-contained — it doesn't
/// need Bishop.Life.Core to be compiled or restored first.
/// </summary>
public sealed class TypeScriptEmitter
{
    private const string Header =
@"// <auto-generated>
// Generated by Bishop.Life.SchemaCodegen from Bishop.Life.Core/Schema (card #1077).
// Edits to this file are overwritten on the next build — change the C# records
// under life/src/Bishop.Life.Core/Schema/ and rebuild Bishop.Life.App instead.
// </auto-generated>
";

    public string Emit(IEnumerable<string> sourceTexts)
    {
        var interfaces = new List<InterfaceModel>();
        var enums = new List<EnumModel>();

        foreach (var text in sourceTexts)
        {
            var tree = CSharpSyntaxTree.ParseText(text);
            var root = tree.GetCompilationUnitRoot();
            foreach (var node in root.DescendantNodes())
            {
                switch (node)
                {
                    case RecordDeclarationSyntax rec when IsPublic(rec.Modifiers):
                        interfaces.Add(BuildFromRecord(rec));
                        break;
                    case ClassDeclarationSyntax cls when IsPublic(cls.Modifiers) && !IsStatic(cls.Modifiers):
                        var fromClass = BuildFromClass(cls);
                        if (fromClass.Fields.Count > 0) interfaces.Add(fromClass);
                        break;
                    case EnumDeclarationSyntax enm when IsPublic(enm.Modifiers):
                        enums.Add(BuildFromEnum(enm));
                        break;
                }
            }
        }

        interfaces = interfaces.OrderBy(i => i.Name, StringComparer.Ordinal).ToList();
        enums = enums.OrderBy(e => e.Name, StringComparer.Ordinal).ToList();

        var sb = new StringBuilder();
        sb.Append(Header);
        sb.AppendLine();

        foreach (var e in enums)
        {
            sb.Append("export type ").Append(e.Name).Append(" =");
            for (var i = 0; i < e.Members.Count; i++)
            {
                sb.AppendLine();
                sb.Append("  | \"").Append(e.Members[i]).Append("\"");
                if (i == e.Members.Count - 1) sb.Append(';');
            }
            sb.AppendLine();
            sb.AppendLine();
        }

        for (var idx = 0; idx < interfaces.Count; idx++)
        {
            var iface = interfaces[idx];
            sb.Append("export interface ").Append(iface.Name).AppendLine(" {");
            foreach (var f in iface.Fields)
            {
                sb.Append("  ").Append(f.Name);
                if (f.IsOptional) sb.Append('?');
                sb.Append(": ").Append(f.TsType).AppendLine(";");
            }
            sb.AppendLine("}");
            if (idx != interfaces.Count - 1) sb.AppendLine();
        }

        return sb.ToString();
    }

    private static bool IsPublic(SyntaxTokenList mods) => mods.Any(m => m.IsKind(SyntaxKind.PublicKeyword));
    private static bool IsStatic(SyntaxTokenList mods) => mods.Any(m => m.IsKind(SyntaxKind.StaticKeyword));

    private InterfaceModel BuildFromRecord(RecordDeclarationSyntax rec)
    {
        var fields = new List<FieldModel>();
        // Positional record params.
        if (rec.ParameterList is { } pl)
        {
            foreach (var p in pl.Parameters)
            {
                var name = ResolveJsonName(p.AttributeLists, p.Identifier.ValueText);
                var (tsType, isOptional) = MapType(p.Type!);
                fields.Add(new FieldModel(name, tsType, isOptional));
            }
        }
        // Body properties (rare on records; included for completeness).
        foreach (var prop in rec.Members.OfType<PropertyDeclarationSyntax>())
        {
            if (!IsPublic(prop.Modifiers)) continue;
            var name = ResolveJsonName(prop.AttributeLists, prop.Identifier.ValueText);
            var (tsType, isOptional) = MapType(prop.Type);
            fields.Add(new FieldModel(name, tsType, isOptional));
        }
        return new InterfaceModel(rec.Identifier.ValueText, fields);
    }

    private InterfaceModel BuildFromClass(ClassDeclarationSyntax cls)
    {
        var fields = new List<FieldModel>();
        foreach (var prop in cls.Members.OfType<PropertyDeclarationSyntax>())
        {
            if (!IsPublic(prop.Modifiers)) continue;
            var name = ResolveJsonName(prop.AttributeLists, prop.Identifier.ValueText);
            var (tsType, isOptional) = MapType(prop.Type);
            fields.Add(new FieldModel(name, tsType, isOptional));
        }
        return new InterfaceModel(cls.Identifier.ValueText, fields);
    }

    private EnumModel BuildFromEnum(EnumDeclarationSyntax enm)
    {
        // Mirrors JsonStringEnumConverter(JsonNamingPolicy.CamelCase) which is
        // configured on both WebView2BrowserChannel and the PlanController
        // serializer.
        var members = enm.Members
            .Select(m => ToCamelCase(m.Identifier.ValueText))
            .ToList();
        return new EnumModel(enm.Identifier.ValueText, members);
    }

    private static string ResolveJsonName(SyntaxList<AttributeListSyntax> attrs, string fallbackPascal)
    {
        foreach (var list in attrs)
        {
            foreach (var attr in list.Attributes)
            {
                var name = attr.Name.ToString();
                if (name is "JsonPropertyName" or "JsonPropertyNameAttribute" &&
                    attr.ArgumentList?.Arguments.Count > 0 &&
                    attr.ArgumentList.Arguments[0].Expression is LiteralExpressionSyntax lit &&
                    lit.IsKind(SyntaxKind.StringLiteralExpression))
                {
                    return lit.Token.ValueText;
                }
            }
        }
        return ToCamelCase(fallbackPascal);
    }

    private (string TsType, bool IsOptional) MapType(TypeSyntax type)
    {
        // Nullable<T> or T?
        if (type is NullableTypeSyntax nullable)
        {
            var (inner, _) = MapType(nullable.ElementType);
            return ($"{inner} | null", true);
        }
        if (type is ArrayTypeSyntax arr)
        {
            var (inner, _) = MapType(arr.ElementType);
            return ($"{inner}[]", false);
        }
        if (type is GenericNameSyntax generic)
        {
            var n = generic.Identifier.ValueText;
            if (n is "List" or "IList" or "IReadOnlyList" or "IEnumerable" or "ICollection" or "IReadOnlyCollection"
                && generic.TypeArgumentList.Arguments.Count == 1)
            {
                var (inner, _) = MapType(generic.TypeArgumentList.Arguments[0]);
                return ($"{inner}[]", false);
            }
            if (n is "Dictionary" or "IDictionary" or "IReadOnlyDictionary"
                && generic.TypeArgumentList.Arguments.Count == 2)
            {
                var (keyTs, _) = MapType(generic.TypeArgumentList.Arguments[0]);
                var (valTs, _) = MapType(generic.TypeArgumentList.Arguments[1]);
                // TS index signatures only allow string|number keys; non-string
                // keys would silently coerce so we fall back to Record<string, V>.
                var keyForIndex = keyTs == "string" || keyTs == "number" ? keyTs : "string";
                return ($"Record<{keyForIndex}, {valTs}>", false);
            }
            if (n == "Nullable" && generic.TypeArgumentList.Arguments.Count == 1)
            {
                var (inner, _) = MapType(generic.TypeArgumentList.Arguments[0]);
                return ($"{inner} | null", true);
            }
            // Unknown generic — last-resort.
            return ("unknown", false);
        }
        if (type is PredefinedTypeSyntax pre)
        {
            return (MapPredefined(pre.Keyword.ValueText), false);
        }
        if (type is IdentifierNameSyntax ident)
        {
            return (MapIdentifier(ident.Identifier.ValueText), false);
        }
        if (type is QualifiedNameSyntax q)
        {
            return MapType(q.Right);
        }
        return ("unknown", false);
    }

    private static string MapPredefined(string keyword) => keyword switch
    {
        "string" => "string",
        "bool" => "boolean",
        "byte" or "sbyte" or "short" or "ushort" or "int" or "uint"
            or "long" or "ulong" or "float" or "double" or "decimal" => "number",
        "object" => "unknown",
        _ => "unknown",
    };

    private static string MapIdentifier(string name) => name switch
    {
        "String" => "string",
        "Boolean" => "boolean",
        "Byte" or "SByte" or "Int16" or "UInt16" or "Int32" or "UInt32"
            or "Int64" or "UInt64" or "Single" or "Double" or "Decimal" => "number",
        // Bishop.Life serializes date-likes as ISO strings (no custom converter
        // overrides DateTimeOffset, so System.Text.Json's default ISO 8601 wins).
        "DateTime" or "DateTimeOffset" or "DateOnly" or "TimeOnly"
            or "TimeSpan" or "Guid" or "Uri" => "string",
        _ => name, // assume user-defined Schema type with matching TS name.
    };

    private static string ToCamelCase(string pascal)
    {
        if (string.IsNullOrEmpty(pascal)) return pascal;
        if (pascal.Length == 1) return pascal.ToLowerInvariant();
        // Mirrors JsonNamingPolicy.CamelCase: lowercase the leading run of
        // uppercase characters, but only the first character if the second
        // character is lowercase (so "Id" → "id", "URL" → "uRL"? — actually
        // System.Text.Json's CamelCase lowercases only the first character;
        // we match that single-char rule for simplicity and consistency).
        return char.ToLower(pascal[0], CultureInfo.InvariantCulture) + pascal.Substring(1);
    }

    public sealed record InterfaceModel(string Name, List<FieldModel> Fields);
    public sealed record FieldModel(string Name, string TsType, bool IsOptional);
    public sealed record EnumModel(string Name, List<string> Members);
}
